# Generated by Django 3.2.7 on 2022-03-19 06:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_db',
            name='completed_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 19, 6, 52, 30, 812610, tzinfo=utc)),
        ),
    ]
